### ISSUE TITLE
Gain adjustment?

### ISSUE THREAD

**Issue by pvarney** [dayne/node-red-contrib-rtl_433#15]
Hello! I have been playing around with rtl_433 for several days and recently found this for Node-RED. I have found that I need to add the gain option (-g 20) when using rtl_433 on the command line in order to pick up a signal from some of my sensors. Is there a way to adjust the gain for rtl_433 in Node-RED? I am very new to Node-RED, so please forgive shortcomings in this area. Thanks!

**Comment by Tomadoggy** [comment]
I would suggest you read the basic rtl_433 guides.  You can find all the options available  by going to a command prompt on your Pi and typing in rtl_433 -h.  Once you find what you wish to change, you will have to modify the file that the node red version uses when it starts up...sorry I don't know which one that is.

**Comment by pvarney** [comment]
For anyone coming across this looking for a way to adjust the gain, I found that it can be set globally in /etc/rtl_433.conf. Also, it looks like you can add the command line arguments on line 28 of the js file:

$ grep -n "this.args " ~/.node-red/node_modules/node-red-contrib-rtl_433/rtl_433/rtl_433.js
28:    this.args = ["-F", "json"];
