### ISSUE TITLE
Guidance on which file to modify to alter the rtl_433 options

### ISSUE THREAD

**Issue by Tomadoggy** [dayne/node-red-contrib-rtl_433#17]
I am (somewhat) familiar with how to alter the rtl_433 options when running in a terminal window on my Pi, however now I wish to use these options in what your your node red service reads at startup.  Can you please direct me to which file to modify?

**Comment by dayne** [comment]
@Tomadoggy the latest version of the node lets you set a few more options / parameters. Might review if that solves some of the access to options you were aiming for.  If not perhaps we can identify what other options to add to the node or add ability to pass a config file as an option.

Give latest node a review to see if that has what you need and if not perhaps you can provide an example config file and useage pattern we could test against.  Closing issue for now but feel free to re-open or do a new issue/PR.
