### ISSUE TITLE
rtl install failing 

### ISSUE THREAD

**Issue by isramos** [dayne/node-red-contrib-rtl_433#2]
I installed rtl_433 on my Raspberry Pi using your script, and I got the error below when running it. 

```
usb_open error -3
Please fix the device permissions, e.g. by installing the udev rules file rtl-sdr.rules
```

I was able to fix it by copying `https://github.com/keenerd/rtl-sdr/blob/master/rtl-sdr.rules` to `/etc/udev/rules.d/rtl-sdr.rules` and rebooting the pi.

Please consider updating your script or instructions

Thanks!

**Comment by dayne** [comment]
@isramos Thanks for this issue. 

Do you recall what version of Raspbian/Linux you were running?  I didn't have to do this step on my Raspbian (buster I think) or Ubuntu 18.04 system.

**Comment by dayne** [comment]
Been using this installer on a couple different versions of Raspbian 32 bit and Ubuntu (32bit & 64bit).  

Closing issue but if more details on where there is sadness feel free to re-open.
